filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /opt/airflow/logs/*/*/*/*.log                        # DAG Task 로그
      - /opt/airflow/logs/scheduler/latest/*.log             # 스케줄러 로그
      - /opt/airflow/logs/dag_processor_manager/latest/*.log # DAG Processor 로그
    fields:
      service: airflow
      log_type: dag_logs
    fields_under_root: true
    multiline.pattern: '^Traceback|^Exception|^\s+File'  # 멀티라인 에러 로그 처리
    multiline.negate: true
    multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]

setup.template.name: "airflow-logs"
setup.template.enabled: true
setup.template.pattern: "airflow-*"

setup.ilm.enabled: false

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - drop_event.when.or:
      - equals:
          message: ""
      - regexp:
          message: ".*INFO - DagRun.*created.*"  # 불필요한 메시지 필터링 예시
